routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::prefix('admin')->group(function () {
    Route::namespace("App\Http\Controllers\Admin")->group(function () {
        // Authentication
        Route::middleware(['GuestAdminUser'])->group(function () {
            Route::view('login', 'admin.auth.login')->name('admin.login');
        });

        Route::post('login', 'LoginController@index')
        ->name('admin.auth.login');

        Route::post('logout', 'LogoutController@index')
        ->name('admin.auth.logout');

        // Por hacer: Verificar que solo puedan ingresar usuarios de tipo administrador
        Route::middleware(['CheckAdminUserAuth'])->group(function () {
            Route::view('/', 'admin.welcome')->name('admin.welcome');

            // Home
            Route::resource('/home/banner', 'Home\HomeBannerController', ['as' => 'admin.home'])->only(['edit', 'update']);

            Route::resource('/home/feature', 'Home\HomeFeatureController', ['as' => 'admin.home'])->only(['edit', 'update']);

            Route::resource('/home/rates', 'Home\HomeRateController', ['as' => 'admin.home']);

            // Blog
            Route::resource('/blog/banner', 'Blog\BlogBannerController', ['as' => 'admin.blog'])->only(['edit', 'update']);

            Route::resource('/blog/posts', 'Blog\BlogPostController', ['as' => 'admin.blog']);
        });
    });
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::namespace("App\Http\Controllers\Web")->group(function () {
    Route::get("/", "HomeController@index")->name('web.home');
    Route::post("/request-service", "RequestServiceController@index");

    Route::get("/news", "BlogController@index")->name('web.blog');
     Route::get("/news/{slug}", "BlogController@show")->name('web.blog.show');
    Route::get("/contact", "ContactController@index")->name('web.pqrs');
    Route::post("/contact", "ContactController@store");
    Route::get("contact/thanks", "ContactController@thanks")->name('web.thanks');
});

app/Models/Blog/BlogBanner.php
<?php

namespace App\Models\Blog;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Config;

class BlogBanner extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected $appends = [
        'image_url',
    ];

    private $uploadsFolder;
    private $bannerFolder;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->uploadsFolder = Config::get('web.uploadsFolder');
        $this->bannerFolder = Config::get('web.blog.banner');
    }

    public function getFolderId()
    {
        return ($this->id < 10)?sprintf('%02d', $this->id):$this->id;
    }

    public function getImageUrlAttribute()
    {
        return asset($this->uploadsFolder . '/' . $this->bannerFolder . '/' . $this->getFolderId() . '/' . $this->image);
    }
}

app/Models/Blog/BlogPost.php
<?php

namespace App\Models\Blog;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Config;

class BlogPost extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected $appends = [
        'thumb_image_url',
        'image_url',
    ];

    private $uploadsFolder;
    private $featuresFolder;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->uploadsFolder = Config::get('web.uploadsFolder');
        $this->featuresFolder = Config::get('web.blog.posts');
    }

    public function getFolderId()
    {
        return ($this->id < 10)?sprintf('%02d', $this->id):$this->id;
    }

    public function getThumbImageUrlAttribute()
    {
        return asset($this->uploadsFolder . '/' . $this->featuresFolder . '/' . $this->getFolderId() . '/' . $this->thumb_image);
    }

    public function getImageUrlAttribute()
    {
        return asset($this->uploadsFolder . '/' . $this->featuresFolder . '/' . $this->getFolderId() . '/' . $this->image);
    }

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = Str::slug($value);
    }
}

app/Http/Controllers/Admin/Blog/BlogBannerController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Blog\BlogBanner;
use App\Services\Util\FileService;
use Config;

class BlogBannerController extends Controller
{
    private $mainFolder;
    private $inputFiles;

    public function __construct()
    {
        $this->mainFolder = Config::get('web.blog.banner');
        $this->inputFiles = ['image'];
    }

    public function edit($id)
    {
        $banner = BlogBanner::findOrFail($id);
        return view('admin.sections.blog.banner.edit', compact('banner'));
    }

    public function update(Request $request, $id)
    {
        $banner = BlogBanner::findOrFail($id);

        //Update record
        $banner->update($request->except($this->inputFiles));

        //Save Files
        $fileService = new FileService();
        $fileService->saveFiles($request, $this->inputFiles, $this->mainFolder, $banner);

        return redirect()->route('admin.blog.banner.edit', $banner->id)->withSuccess('Se ha actualizado el banner satisfactoriamente.');
    }
}

app/Http/Controllers/Admin/Blog/BlogPostController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Admin\Blog\BlogPostRequest;
use App\Models\Blog\BlogPost;
use App\Services\Util\FileService;
use Config;

class BlogPostController extends Controller
{
    private $mainFolder;
    private $inputFiles;

    public function __construct()
    {
        $this->mainFolder = Config::get('web.blog.posts');
        $this->inputFiles = ['thumb_image', 'image'];
    }

    public function index()
    {
        $posts = BlogPost::latest('id')->paginate(6);
        return view('admin.sections.blog.posts.index', compact('posts'));
    }

    public function create()
    {
        $post = new BlogPost;
        return view('admin.sections.blog.posts.create', compact('post'));
    }

    public function store(BlogPostRequest $request)
    {
        $post = BlogPost::create($request->except($this->inputFiles));

        //Save Files
        $fileService = new FileService();
        $fileService->saveFiles($request, $this->inputFiles, $this->mainFolder, $post);

        return redirect()->route('admin.blog.posts.index')->withSuccess('Se ha creado el artículo ' . $post->title . '.');
    }

    public function edit($id)
    {
        $post = BlogPost::findOrFail($id);
        return view('admin.sections.blog.posts.edit', compact('post'));
    }

    public function update(BlogPostRequest $request, $id)
    {
        $post = BlogPost::findOrFail($id);

        //Update record
        $post->update($request->except($this->inputFiles));

        //Save Files
        $fileService = new FileService();
        $fileService->saveFiles($request, $this->inputFiles, $this->mainFolder, $post);

        return redirect()->route('admin.blog.posts.edit', $post->id)->withSuccess('Se ha actualizado el artículo satisfactoriamente.');
    }

    public function destroy($id)
    {
        $post = BlogPost::findOrFail($id);
        $title = $post->title;
        $fileService = new FileService();
        $path = $this->mainFolder . '/'. $post->getFolderId();
        $fileService->deleteDirectory($path);
        $post->delete();

        return redirect()->route('admin.blog.posts.index')->withSuccess('El artículo ' . $title . ' ha sido eliminado satisfactoriamente.');
    }
}

app/Http/Controllers/Web/BlogController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Blog\BlogBanner;
use App\Models\Blog\BlogPost;

class BlogController extends Controller
{
    public function index()
    {
        $blogBanner = BlogBanner::first();
        $blogPosts = BlogPost::latest('id')->paginate(6);
        return view('web.blog-list', compact('blogBanner', 'blogPosts'));
    }

    public function show($slug)
    {
        $blogPost = BlogPost::where('slug', $slug)->first();
        return view('web.blog', compact('blogPost'));
    }
}

resources/views/admin/sections/blog/banner/edit.blade.php
@extends('admin.layouts.master')
@section('content')

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-md-flex align-items-center justify-content-between">
            <h4 class="mb-0">Banner</h4>

            {{-- <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{{ route('admin.blog.banner.index') }}">Banner principal</a></li>
                    <li class="breadcrumb-item active">Editar</li>
                </ol>
            </div> --}}
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        @include('admin.components.success-message')
        @include('admin.components.errors-form')

        <div class="card">
            <div class="card-body">
                {!! Form::open(['route' => ['admin.blog.banner.update', $banner->id], 'method' => 'put', 'files' => true]) !!}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="form-label">Title</label>
                                {!! Form::text('title', $banner->title , ['class' => 'form-control', 'maxlength' => '191']) !!}
                            </div>
                        </div>

                        <div class="col-md-6">
                            <label class="form-label">Description</label>
                            {!! Form::text('description', $banner->description , ['class' => 'form-control', 'maxlength' => '191']) !!}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="form-label">Image</label><br>
                                {!! Form::file('image') !!}
                                @if($banner->image)
                                    <img src="{{ $banner->image_url }}" width="50" alt="">
                                @endif
                            </div>
                        </div>

                    </div>

                    <button type="submit" class="btn btn-primary">Save</button>
                {!! Form::close() !!}
            </div>
        </div>
    </div> <!-- end col -->
</div>
<!-- end row -->

@endsection