routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::prefix('admin')->group(function () {
    Route::namespace("App\Http\Controllers\Admin")->group(function () {
        // Authentication
        Route::middleware(['GuestAdminUser'])->group(function () {
            Route::view('login', 'admin.auth.login')->name('admin.login');
        });

        Route::post('login', 'LoginController@index')
        ->name('admin.auth.login');

        Route::post('logout', 'LogoutController@index')
        ->name('admin.auth.logout');

        // Por hacer: Verificar que solo puedan ingresar usuarios de tipo administrador
        Route::middleware(['CheckAdminUserAuth'])->group(function () {
            Route::view('/', 'admin.welcome')->name('admin.welcome');

            // Home
            Route::resource('/home/banner', 'Home\HomeBannerController', ['as' => 'admin.home'])->only(['edit', 'update']);

            Route::resource('/home/feature', 'Home\HomeFeatureController', ['as' => 'admin.home'])->only(['edit', 'update']);

            Route::resource('/home/rates', 'Home\HomeRateController', ['as' => 'admin.home']);

            // Blog
            Route::resource('/blog/banner', 'Blog\BlogBannerController', ['as' => 'admin.blog'])->only(['edit', 'update']);

            Route::resource('/blog/posts', 'Blog\BlogPostController', ['as' => 'admin.blog']);
        });
    });
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::namespace("App\Http\Controllers\Web")->group(function () {
    Route::get("/", "HomeController@index")->name('web.home');
    Route::post("/request-service", "RequestServiceController@index");

    Route::get("/news", "BlogController@index")->name('web.blog');
     Route::get("/news/{slug}", "BlogController@show")->name('web.blog.show');
    Route::get("/contact", "ContactController@index")->name('web.pqrs');
    Route::post("/contact", "ContactController@store");
    Route::get("contact/thanks", "ContactController@thanks")->name('web.thanks');
});

app/Models/Home/HomeBanner.php
<?php

namespace App\Models\Home;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Config;

class HomeBanner extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected $appends = [
        'image_url',
    ];

    private $uploadsFolder;
    private $bannerFolder;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->uploadsFolder = Config::get('web.uploadsFolder');
        $this->bannerFolder = Config::get('web.home.banner');
    }

    public function getFolderId()
    {
        return ($this->id < 10)?sprintf('%02d', $this->id):$this->id;
    }

    public function getImageUrlAttribute()
    {
        return asset($this->uploadsFolder . '/' . $this->bannerFolder . '/' . $this->getFolderId() . '/' . $this->image);
    }
}

app/Models/Home/HomeFeature.php
<?php

namespace App\Models\Home;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Config;

class HomeFeature extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected $appends = [
        'image_url',
    ];

    private $uploadsFolder;
    private $featureFolder;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->uploadsFolder = Config::get('web.uploadsFolder');
        $this->featureFolder = Config::get('web.home.feature');
    }

    public function getFolderId()
    {
        return ($this->id < 10)?sprintf('%02d', $this->id):$this->id;
    }

    public function getImageUrlAttribute()
    {
        return asset($this->uploadsFolder . '/' . $this->featureFolder . '/' . $this->getFolderId() . '/' . $this->image);
    }
}

app/Http/Controllers/Admin/Home/HomeBannerController.php
<?php

namespace App\Http\Controllers\Admin\Home;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Home\HomeBanner;
use App\Services\Util\FileService;
use Config;

class HomeBannerController extends Controller
{
    private $mainFolder;
    private $inputFiles;

    public function __construct()
    {
        $this->mainFolder = Config::get('web.home.banner');
        $this->inputFiles = ['image'];
    }

    public function edit($id)
    {
        $banner = HomeBanner::findOrFail($id);
        return view('admin.sections.home.banner.edit', compact('banner'));
    }

    public function update(Request $request, $id)
    {
        $banner = HomeBanner::findOrFail($id);

        //Update record
        $banner->update($request->except($this->inputFiles));

        //Save Files
        $fileService = new FileService();
        $fileService->saveFiles($request, $this->inputFiles, $this->mainFolder, $banner);

        return redirect()->route('admin.home.banner.edit', $banner->id)->withSuccess('Se ha actualizado el banner satisfactoriamente.');
    }
}

app/Http/Controllers/Admin/Home/HomeFeatureController.php
<?php

namespace App\Http\Controllers\Admin\Home;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Home\HomeFeature;
use App\Services\Util\FileService;
use Config;

class HomeFeatureController extends Controller
{
    private $mainFolder;
    private $inputFiles;

    public function __construct()
    {
        $this->mainFolder = Config::get('web.home.feature');
        $this->inputFiles = ['image'];
    }

    public function edit($id)
    {
        $feature = HomeFeature::findOrFail($id);
        return view('admin.sections.home.feature.edit', compact('feature'));
    }

    public function update(Request $request, $id)
    {
        $feature = HomeFeature::findOrFail($id);

        //Update record
        $feature->update($request->except($this->inputFiles));

        //Save Files
        $fileService = new FileService();
        $fileService->saveFiles($request, $this->inputFiles, $this->mainFolder, $feature);

        return redirect()->route('admin.home.feature.edit', $feature->id)->withSuccess('Se ha actualizado el destacado satisfactoriamente.');
    }
}

app/Http/Controllers/Web/HomeController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Home\HomeBanner;
use App\Models\Home\HomeFeature;
use App\Models\Home\HomeRate;
use Illuminate\Support\Facades\Mail;
use App\Mail\ServiceRequestMail;
use App\Http\Requests\Web\ServiceRequest;

class HomeController extends Controller
{
    public function index()
    {
        $homeBanner = HomeBanner::first();
        $homeFeature = HomeFeature::first();
        return view('web.home', compact('homeBanner', 'homeFeature'));
    }
}

resources/views/admin/sections/home/rates/create.blade.php
@extends('admin.layouts.master')
@section('content')

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Crear tarifa</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{{ route('admin.home.rates.index') }}">Tarifas</a></li>
                    <li class="breadcrumb-item active">Crear</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        @include('admin.components.success-message')
        @include('admin.components.errors-form')

        <div class="card">
            <div class="card-body">
                {!! Form::open(['route' => ['admin.home.rates.store', $rate->id ], 'method' => 'post', 'files' => true]) !!}

                    @include('admin.sections.home.rates.form')

                {!! Form::close() !!}
            </div>
        </div>
    </div> <!-- end col -->
</div>
<!-- end row -->

@endsection

resources/views/admin/sections/home/rates/edit.blade.php
@extends('admin.layouts.master')
@section('content')

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-md-flex align-items-center justify-content-between">
            <h4 class="mb-0">Editar Tarifa</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{{ route('admin.home.rates.index') }}">Tarifas</a></li>
                    <li class="breadcrumb-item active">Editar</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        @include('admin.components.success-message')
        @include('admin.components.errors-form')

        <div class="card">
            <div class="card-body">
                {!! Form::open(['route' => ['admin.home.rates.update', $rate->id], 'method' => 'put', 'files' => true]) !!}

                     @include('admin.sections.home.rates.form')

                {!! Form::close() !!}
            </div>
        </div>
    </div> <!-- end col -->
</div>
<!-- end row -->

@endsection

resources/views/admin/sections/home/rates/form.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="form-label">Texto Botón</label>
            {!! Form::text('button_text', $rate->button_text , ['class' => 'form-control', 'maxlength' => '191']) !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label class="form-label">Zona</label><br>
             {!! Form::select('zone',['tarifas zona centro' => 'tarifas zona centro', 'tarifas llanos orientales' =>  'tarifas llanos orientales'], $rate->zone , ['class' => 'form-control']) !!}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="form-label">Archivo</label><br>
            {!! Form::file('file') !!}
            @if($rate->file)
                <a href="{{ $rate->file_url }}" target="blank">Ver archivo</a>
            @endif
        </div>
    </div>
</div>

<button type="submit" class="btn btn-primary">Guardar</button>

resources/views/admin/sections/home/rates/index.blade.php
@extends('admin.layouts.master')
@section('content')

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Tarifas</h4>

            {{-- <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Forms</a></li>
                    <li class="breadcrumb-item active">Basic Elements</li>
                </ol>
            </div> --}}

        </div>
    </div>
    <div class="col-12">
        <a href="{{ route('admin.home.rates.create') }}" class="btn btn-primary">Crear</a><br><br>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                    @include('admin.components.success-message')

                    <div class="table-responsive">
                        <table class="table table-hover">
                          <thead class="thead-dark">
                            <tr>
                              <th scope="col">#</th>
                              <th scope="col">Nombre</th>
                              <th scope="col">Acciones</th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($rates as $rate)
                              <tr>
                                <td>{{ $rate->id }}</td>
                                <td>{{ $rate->button_text }}</td>
                                <td>
                                    {!! Form::open(['route' => ['admin.home.rates.destroy', $rate->id], 'method' => 'delete', 'class' => 'form-delete-record']) !!}
                                        <a href="{{ route('admin.home.rates.edit', $rate->id) }}" class="btn btn-primary">Editar</a>

                                        <button type="submit" class="btn btn-danger delete-record">Eliminar</button>
                                    {!! Form::close() !!}

                               </td>
                              </tr>
                            @endforeach
                          </tbody>
                        </table>
                    </div>
            </div>
        </div>
    </div> <!-- end col -->
</div>
<!-- end row -->

@endsection