routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::prefix('admin')->group(function () {
    Route::namespace("App\Http\Controllers\Admin")->group(function () {
        // Authentication
        Route::middleware(['GuestAdminUser'])->group(function () {
            Route::view('login', 'admin.auth.login')->name('admin.login');
        });

        Route::post('login', 'LoginController@index')
        ->name('admin.auth.login');

        Route::post('logout', 'LogoutController@index')
        ->name('admin.auth.logout');

        // Por hacer: Verificar que solo puedan ingresar usuarios de tipo administrador
        Route::middleware(['CheckAdminUserAuth'])->group(function () {
            Route::view('/', 'admin.welcome')->name('admin.welcome');

            // Home
            Route::resource('/home/banner', 'Home\HomeBannerController', ['as' => 'admin.home'])->only(['edit', 'update']);

            Route::resource('/home/feature', 'Home\HomeFeatureController', ['as' => 'admin.home'])->only(['edit', 'update']);

            Route::resource('/home/rates', 'Home\HomeRateController', ['as' => 'admin.home']);

            // Blog
            Route::resource('/blog/banner', 'Blog\BlogBannerController', ['as' => 'admin.blog'])->only(['edit', 'update']);

            Route::resource('/blog/posts', 'Blog\BlogPostController', ['as' => 'admin.blog']);
        });
    });
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::namespace("App\Http\Controllers\Web")->group(function () {
    Route::get("/", "HomeController@index")->name('web.home');
    Route::post("/request-service", "RequestServiceController@index");

    Route::get("/news", "BlogController@index")->name('web.blog');
     Route::get("/news/{slug}", "BlogController@show")->name('web.blog.show');
    Route::get("/contact", "ContactController@index")->name('web.pqrs');
    Route::post("/contact", "ContactController@store");
    Route::get("contact/thanks", "ContactController@thanks")->name('web.thanks');
});

resources/views/admin/components/errors-form.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach

        </ul>
    </div>
@endif

resources/views/admin/components/menu.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ route('web.home') }}">
            {{ config('app.name') }}
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"
                       id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Home
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item"
                               href="{{ route('admin.home.banner.edit', 1) }}">Banner</a>
                        </li>
                        <li>
                            <a class="dropdown-item"
                               href="{{ route('admin.home.feature.edit', 1) }}">Feature</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"
                       id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Blog
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item"
                               href="{{ route('admin.blog.banner.edit', 1) }}">Banner</a>
                        </li>
                        <li>
                            <a class="dropdown-item"
                               href="{{ route('admin.blog.posts.index') }}">Posts</a>
                        </li>
                    </ul>
                </li>
            </ul>

            <ul class="navbar-nav me-aut mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"
                       id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {{ Auth::user()->name }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end"
                        aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="#"
                               onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                                Logout
                            </a>
                            <form id="logout-form"
                                  action="{{ route('admin.auth.logout') }}"
                                  method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>
                <!-- <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
            </li> -->
            </ul>
        </div>
    </div>
</nav>

resources/views/admin/components/success-message.blade.php
@if (Session::has('success'))
    <div class="alert alert-success alert-dismissible fade show">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <p>{{ Session::get('success') }}</p>
    </div>
@endif